version: '3.6'

services:
  frontend:
    container_name: ${CONTAINER_NAME}
    image: fingerstyle-frontend-dev
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
