import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FingerStyle Taiwan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpg" />
      </Head>

      <main className={styles.main}>
        <div className={styles.titleWrapper}>
          <img className={styles.logoImg} src="/logo.jpg" width="150"/>
          <h1 className={styles.title}>
            FingerStyle Taiwan
          </h1>
        </div>
        <div className={styles.description}>
          coming soon...
        </div>
      </main>
    </div>
  )
}

export default Home
